init for binary build check and key gen function in client
Hyperledger-TWGC/GM-interoperability pull request #25
Opened 2021-07-17 03:05 UTC by SamYuan1990

update in e2e test
init for binary build check and key gen function in client

Signed-off-by: Sam Yuan <yy19902439@126.com>

2021-07-17 11:31 UTC, xiaohui249 requested changes

2021-07-17 11:31 UTC, xiaohui249 commented on workshop/README-zh.md
>  1. 生成密钥并配置
标题序号是否有问题？

2021-07-17 11:31 UTC, xiaohui249 commented on workshop/README-zh.md
>  1. 启动服务器
同上

2021-07-17 11:31 UTC, xiaohui249 commented on workshop/client/client.go
>  	"github.com/Hyperledger-TWGC/fabric-gm-plugins/workshop"
在github上没有找到fabric-gm-plugins这个库

2021-07-17 11:52 UTC, SamYuan1990 commented on workshop/README-zh.md
>  1. 生成密钥并配置
readme able to use 
1. aaa
1. bbb

equals to

1. aaa
2. bbb

2021-07-17 11:52 UTC, SamYuan1990 commented on workshop/client/client.go
>  	"github.com/Hyperledger-TWGC/fabric-gm-plugins/workshop"
https://github.com/Hyperledger-TWGC/GM-interoperability/blob/master/interop/go.mod#L1

here your are

2021-07-18 02:10 UTC, xiaohui249 approved these changes

2021-07-23 13:10 UTC, merged